 const STORYBLOK_TOKEN = "QPpeHjrb57ZtQMm9RdkBYQtt";

 const STORYBLOK_BASIC_SERVER_URL = "https://api.storyblok.com/v2/cdn/stories";

const STORYBLOK_SERVER_URL = `${STORYBLOK_BASIC_SERVER_URL}?token=${STORYBLOK_TOKEN}`;


module.exports = {STORYBLOK_TOKEN, STORYBLOK_SERVER_URL, STORYBLOK_BASIC_SERVER_URL }